<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>
<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling Informations') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if (!empty($order->getTracksCollection())) : ?>
        <?php $url =  $this->helper('jframeworks\shippingtracking\Helper\Data')
            ->getTrackingPopupUrlBySalesModel($order);
                        $goodUrl = str_replace('/admin/', '/', $url);
                    ?>
            <p><a href="#" id="linkId" onclick="popWin('<?php
                echo $goodUrl;
            ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php
                /* @escapeNotVerified */ echo __('Track Order Shipment(s)') ?>"><?php
                /* @escapeNotVerified */ echo __('Track Order Shipment(s)') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()) : ?>
            <strong><?php echo $block->escapeHtml($order->getShippingDescription()) ?></strong>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) : ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else : ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>
            <?php /* @escapeNotVerified */ echo $_excl; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl) : ?>
                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
            <?php endif; ?>
        <?php else : ?>
            <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
        <?php endif; ?>
    </div>
</div>